export const SPACING = {
  _1: 4,
  _2: 8,
  _3: 12,
  _4: 16,
  _5: 24,
  _6: 32,
  _7: 48,
  _8: 64,
};

// Grid
export const GRID_ROW_MIN_HEIGHT = 92;
export const GRID_ROW_MAX_HEIGHT = 100;
export const GRID_SPACING = SPACING._5;

// Animation
export const GRID_ANIMATION_DURATION_MS = 400;
export const GRID_ANIMATION_DURATION_SEC = GRID_ANIMATION_DURATION_MS / 1000;
export const FADE_IN_DURATION = 0.2;

// Layout
export const CONTENT_MAX_WIDTH = 1200;
export const CONTENT_MAX_WIDTH_TABLET = 800;
export const CONTENT_MAX_WIDTH_MOBILE = 400;
export const PAGE_HORIZONTAL_PADDING = SPACING._8;
export const PAGE_HORIZONTAL_PADDING_TABLET = SPACING._7;

export const MEDIA_QUERY = {
  GRID_DESKTOP: CONTENT_MAX_WIDTH + 2 * PAGE_HORIZONTAL_PADDING,
  TABLET: 1100,
  GRID_TABLET: CONTENT_MAX_WIDTH_TABLET + 2 * PAGE_HORIZONTAL_PADDING_TABLET,
  MOBILE: 700,
};
