export enum GridItemType {
  Name = "name",
  Info = "info",
  About = "about",
  Image = "image",
  Email = "email",
  Social = "social",
  Work = "work",
  WorkStatic = "work-static",
  Skills = "skills",
  SkillsStatic = "skills-static",
  References = "references",
  ReferencesStatic = "references-static",
  Education = "education",
  Languages = "languages",
}
